// frontend/src/app/pages/dashboard/documents/documents.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../../shared/services/api.service';
import { VarianceRequestSummary, STATUS_CSS, STATUS_LABELS } from '../../../shared/models/variance-request.model';

@Component({
  selector: 'app-documents',
  standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <div style="padding:2rem">
      <div style="margin-bottom:2rem">
        <h1 style="font-size:1.5rem;font-weight:700;margin-bottom:0.25rem">Variance Documents</h1>
        <p style="font-size:0.875rem;color:var(--rr-muted)">AI-generated 27-page regulated variance packages</p>
      </div>

      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem">
        <div class="card" style="border-left:3px solid var(--rr-gold)">
          <p style="font-size:0.75rem;color:var(--rr-muted);text-transform:uppercase;letter-spacing:0.05em;margin-bottom:0.5rem">Total Documents</p>
          <p style="font-size:2rem;font-weight:700">{{ documentedRequests.length }}</p>
        </div>
        <div class="card" style="border-left:3px solid #10B981">
          <p style="font-size:0.75rem;color:var(--rr-muted);text-transform:uppercase;letter-spacing:0.05em;margin-bottom:0.5rem">Approved</p>
          <p style="font-size:2rem;font-weight:700">{{ approvedCount }}</p>
        </div>
        <div class="card" style="border-left:3px solid #3B82F6">
          <p style="font-size:0.75rem;color:var(--rr-muted);text-transform:uppercase;letter-spacing:0.05em;margin-bottom:0.5rem">Avg AI Contribution</p>
          <p style="font-size:2rem;font-weight:700">65%</p>
        </div>
      </div>

      <div class="card" style="padding:0;overflow:hidden">
        <table style="width:100%;border-collapse:collapse">
          <thead>
            <tr style="background:var(--rr-platinum)">
              <th class="th">Reference</th>
              <th class="th">Title</th>
              <th class="th">Engine</th>
              <th class="th">MRO</th>
              <th class="th">Status</th>
              <th class="th">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let r of documentedRequests" style="border-top:1px solid var(--rr-border)">
              <td class="td" style="font-weight:500">{{ r.referenceNumber }}</td>
              <td class="td" style="max-width:250px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ r.title }}</td>
              <td class="td muted">{{ r.engineType }}</td>
              <td class="td muted">{{ r.mroOrganisation }}</td>
              <td class="td"><span class="badge" [ngClass]="getStatusCss(r.status)">{{ getStatusLabel(r.status) }}</span></td>
              <td class="td">
                <a [routerLink]="['/dashboard/requests', r.id]" style="font-size:0.8125rem;color:var(--rr-navy);font-weight:500">View</a>
              </td>
            </tr>
          </tbody>
        </table>
        <div *ngIf="documentedRequests.length === 0" style="padding:3rem;text-align:center;color:var(--rr-muted)">
          No variance documents generated yet.
        </div>
      </div>

      <div class="card" style="margin-top:2rem;background:linear-gradient(135deg,#001233 0%,#001845 100%);color:#fff">
        <h3 style="font-size:1rem;font-weight:600;margin-bottom:0.75rem">Document Authoring Agent</h3>
        <p style="font-size:0.875rem;line-height:1.6;color:rgba(255,255,255,0.7);margin-bottom:1rem">
          The Document Authoring Agent uses RAG over 15,000+ prior variances to generate
          comprehensive 27-page regulated variance packages. Each document includes:
        </p>
        <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:0.75rem">
          <div *ngFor="let section of documentSections" style="display:flex;align-items:center;gap:0.5rem">
            <div style="width:6px;height:6px;border-radius:50%;background:var(--rr-gold)"></div>
            <span style="font-size:0.8125rem;color:rgba(255,255,255,0.8)">{{ section }}</span>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .th { text-align:left;padding:0.625rem 0.75rem;font-size:0.6875rem;font-weight:600;color:var(--rr-muted);text-transform:uppercase;letter-spacing:0.05em; }
    .td { padding:0.625rem 0.75rem;font-size:0.8125rem; }
    .muted { color: var(--rr-muted); }
  `]
})
export class DocumentsComponent implements OnInit {
  documentedRequests: VarianceRequestSummary[] = [];
  approvedCount = 0;

  getStatusCss(status: string): string { return STATUS_CSS[status] || status.toLowerCase(); }
  getStatusLabel(status: string): string { return STATUS_LABELS[status] || status; }

  documentSections = [
    'Problem Statement',
    'Technical Analysis',
    'Safety Assessment',
    'Proposed Disposition',
    'Regulatory References',
    'Specialist Recommendation',
    'Applicable Regulations',
    'Digital Signatures'
  ];

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.api.getRequests({ page: 1, pageSize: 50 }).subscribe(r => {
      this.documentedRequests = r.items.filter(i =>
        ['DocumentAuthored', 'Approved', 'Completed'].includes(i.status)
      );
      this.approvedCount = r.items.filter(i =>
        ['Approved', 'Completed'].includes(i.status)
      ).length;
    });
  }
}

// frontend/src/pages/dashboard/documents/Documents.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import * as api from '../../../shared/services/api';
import type { VarianceRequestSummary } from '../../../shared/models/variance-request.model';
import { STATUS_CSS, STATUS_LABELS } from '../../../shared/models/variance-request.model';
import './Documents.scss';

const documentSections = [
  'Problem Statement',
  'Technical Analysis',
  'Safety Assessment',
  'Proposed Disposition',
  'Regulatory References',
  'Specialist Recommendation',
  'Applicable Regulations',
  'Digital Signatures',
];

function Documents() {
  const [documentedRequests, setDocumentedRequests] = useState<VarianceRequestSummary[]>([]);
  const [approvedCount, setApprovedCount] = useState(0);

  useEffect(() => {
    api.getRequests({ page: 1, pageSize: 50 }).then(r => {
      setDocumentedRequests(r.items.filter(i =>
        ['DocumentAuthored', 'Approved', 'Completed'].includes(i.status)
      ));
      setApprovedCount(r.items.filter(i =>
        ['Approved', 'Completed'].includes(i.status)
      ).length);
    });
  }, []);

  const getStatusCss = (status: string) => STATUS_CSS[status] || status.toLowerCase();
  const getStatusLabel = (status: string) => STATUS_LABELS[status] || status;

  return (
    <div style={{ padding: '2rem' }}>
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.25rem' }}>Variance Documents</h1>
        <p style={{ fontSize: '0.875rem', color: 'var(--rr-muted)' }}>AI-generated 27-page regulated variance packages</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '1rem', marginBottom: '2rem' }}>
        <div className="card" style={{ borderLeft: '3px solid var(--rr-gold)' }}>
          <p style={{ fontSize: '0.75rem', color: 'var(--rr-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Total Documents</p>
          <p style={{ fontSize: '2rem', fontWeight: 700 }}>{documentedRequests.length}</p>
        </div>
        <div className="card" style={{ borderLeft: '3px solid #10B981' }}>
          <p style={{ fontSize: '0.75rem', color: 'var(--rr-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Approved</p>
          <p style={{ fontSize: '2rem', fontWeight: 700 }}>{approvedCount}</p>
        </div>
        <div className="card" style={{ borderLeft: '3px solid #3B82F6' }}>
          <p style={{ fontSize: '0.75rem', color: 'var(--rr-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Avg AI Contribution</p>
          <p style={{ fontSize: '2rem', fontWeight: 700 }}>65%</p>
        </div>
      </div>

      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: 'var(--rr-platinum)' }}>
              <th className="th">Reference</th>
              <th className="th">Title</th>
              <th className="th">Engine</th>
              <th className="th">MRO</th>
              <th className="th">Status</th>
              <th className="th">Actions</th>
            </tr>
          </thead>
          <tbody>
            {documentedRequests.map(r => (
              <tr key={r.id} style={{ borderTop: '1px solid var(--rr-border)' }}>
                <td className="td" style={{ fontWeight: 500 }}>{r.referenceNumber}</td>
                <td className="td" style={{ maxWidth: '250px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</td>
                <td className="td muted">{r.engineType}</td>
                <td className="td muted">{r.mroOrganisation}</td>
                <td className="td"><span className={`badge ${getStatusCss(r.status)}`}>{getStatusLabel(r.status)}</span></td>
                <td className="td">
                  <Link to={`/dashboard/requests/${r.id}`} style={{ fontSize: '0.8125rem', color: 'var(--rr-navy)', fontWeight: 500 }}>View</Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {documentedRequests.length === 0 && (
          <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--rr-muted)' }}>
            No variance documents generated yet.
          </div>
        )}
      </div>

      <div className="card" style={{ marginTop: '2rem', background: 'linear-gradient(135deg,#001233 0%,#001845 100%)', color: '#fff' }}>
        <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.75rem' }}>Document Authoring Agent</h3>
        <p style={{ fontSize: '0.875rem', lineHeight: 1.6, color: 'rgba(255,255,255,0.7)', marginBottom: '1rem' }}>
          The Document Authoring Agent uses RAG over 15,000+ prior variances to generate
          comprehensive 27-page regulated variance packages. Each document includes:
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: '0.75rem' }}>
          {documentSections.map(section => (
            <div key={section} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--rr-gold)' }}></div>
              <span style={{ fontSize: '0.8125rem', color: 'rgba(255,255,255,0.8)' }}>{section}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Documents;
