// frontend/src/pages/dashboard/requests/Requests.tsx
import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import * as api from '../../../shared/services/api';
import { VarianceRequestSummary, STATUS_LABELS, STATUS_CSS } from '../../../shared/models/variance-request.model';
import './Requests.scss';

function Requests() {
  const navigate = useNavigate();
  const [requests, setRequests] = useState<VarianceRequestSummary[]>([]);
  const [engineTypes, setEngineTypes] = useState<string[]>([]);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  const [engineFilter, setEngineFilter] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 20;
  const [totalCount, setTotalCount] = useState(0);
  const totalPages = Math.ceil(totalCount / pageSize);

  const statusOptions = Object.entries(STATUS_LABELS).map(([value, label]) => ({ value, label }));

  const loadRequests = (p = page, s = search, st = statusFilter, pr = priorityFilter, eng = engineFilter) => {
    api.getRequests({
      page: p, pageSize,
      status: st || undefined,
      priority: pr || undefined,
      engineType: eng || undefined,
      search: s || undefined,
      sortBy: 'createdAt', sortDir: 'desc',
    }).then(r => {
      setRequests(r.items);
      setTotalCount(r.totalCount);
    });
  };

  useEffect(() => {
    api.getEngineTypes().then(setEngineTypes);
    loadRequests();
  }, []);

  const onFilter = (field: string, value: string) => {
    const ns = field === 'search' ? value : search;
    const nst = field === 'status' ? value : statusFilter;
    const npr = field === 'priority' ? value : priorityFilter;
    const ne = field === 'engine' ? value : engineFilter;
    if (field === 'search') setSearch(value);
    if (field === 'status') setStatusFilter(value);
    if (field === 'priority') setPriorityFilter(value);
    if (field === 'engine') setEngineFilter(value);
    setPage(1);
    loadRequests(1, ns, nst, npr, ne);
  };

  const changePage = (p: number) => { setPage(p); loadRequests(p); };

  const getStatusLabel = (s: string) => STATUS_LABELS[s] || s;
  const getStatusCss = (s: string) => STATUS_CSS[s] || '';
  const formatDate = (d: string) => new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  return (
    <div style={{ padding: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.25rem' }}>Variance Requests</h1>
          <p style={{ fontSize: '0.875rem', color: 'var(--rr-muted)' }}>{totalCount} requests across the MRO network</p>
        </div>
        <Link to="/dashboard/submit" className="btn-navy">New Request</Link>
      </div>

      <div className="card" style={{ marginBottom: '1rem', padding: '1rem' }}>
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
          <input type="text" value={search} onChange={e => onFilter('search', e.target.value)} placeholder="Search requests..."
            style={{ flex: 1, minWidth: '200px', padding: '0.5rem 0.75rem', fontSize: '0.8125rem', border: '1px solid var(--rr-border)', borderRadius: '0.375rem' }} />
          <select value={statusFilter} onChange={e => onFilter('status', e.target.value)} style={{ padding: '0.5rem 0.75rem', fontSize: '0.8125rem', border: '1px solid var(--rr-border)', borderRadius: '0.375rem' }}>
            <option value="">All Statuses</option>
            {statusOptions.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}
          </select>
          <select value={priorityFilter} onChange={e => onFilter('priority', e.target.value)} style={{ padding: '0.5rem 0.75rem', fontSize: '0.8125rem', border: '1px solid var(--rr-border)', borderRadius: '0.375rem' }}>
            <option value="">All Priorities</option>
            <option value="Critical">Critical</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
          <select value={engineFilter} onChange={e => onFilter('engine', e.target.value)} style={{ padding: '0.5rem 0.75rem', fontSize: '0.8125rem', border: '1px solid var(--rr-border)', borderRadius: '0.375rem' }}>
            <option value="">All Engines</option>
            {engineTypes.map(e => <option key={e} value={e}>{e}</option>)}
          </select>
        </div>
      </div>

      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: 'var(--rr-platinum)' }}>
              <th className="th">Reference</th>
              <th className="th">Title</th>
              <th className="th">Anomaly</th>
              <th className="th">Engine</th>
              <th className="th">MRO</th>
              <th className="th">Status</th>
              <th className="th">Priority</th>
              <th className="th">Date</th>
            </tr>
          </thead>
          <tbody>
            {requests.map(r => (
              <tr key={r.id} onClick={() => navigate(`/dashboard/requests/${r.id}`)} className="table-row">
                <td className="td" style={{ fontWeight: 500 }}>{r.referenceNumber}</td>
                <td className="td" style={{ maxWidth: '220px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</td>
                <td className="td muted">{r.anomalyType}</td>
                <td className="td muted">{r.engineType}</td>
                <td className="td muted" style={{ maxWidth: '140px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.mroOrganisation}</td>
                <td className="td"><span className={`badge ${getStatusCss(r.status)}`}>{getStatusLabel(r.status)}</span></td>
                <td className="td"><span className={`badge ${r.priority.toLowerCase()}`}>{r.priority}</span></td>
                <td className="td muted">{formatDate(r.createdAt)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {totalCount > pageSize && (
        <div style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', marginTop: '1rem' }}>
          <button className="btn-outline" onClick={() => changePage(page - 1)} disabled={page <= 1} style={{ padding: '0.375rem 0.75rem', fontSize: '0.8125rem' }}>Prev</button>
          <span style={{ padding: '0.375rem 0.75rem', fontSize: '0.8125rem', color: 'var(--rr-muted)' }}>{page} / {totalPages}</span>
          <button className="btn-outline" onClick={() => changePage(page + 1)} disabled={page >= totalPages} style={{ padding: '0.375rem 0.75rem', fontSize: '0.8125rem' }}>Next</button>
        </div>
      )}
    </div>
  );
}

export default Requests;

// frontend/src/app/pages/dashboard/requests/requests.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../../shared/services/api.service';
import { VarianceRequestSummary, STATUS_LABELS, STATUS_CSS } from '../../../shared/models/variance-request.model';

@Component({
  selector: 'app-requests',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div style="padding:2rem">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1.5rem">
        <div>
          <h1 style="font-size:1.5rem;font-weight:700;margin-bottom:0.25rem">Variance Requests</h1>
          <p style="font-size:0.875rem;color:var(--rr-muted)">{{ totalCount }} requests across the MRO network</p>
        </div>
        <a routerLink="/submit" class="btn-navy">New Request</a>
      </div>

      <div class="card" style="margin-bottom:1rem;padding:1rem">
        <div style="display:flex;gap:0.75rem;flex-wrap:wrap">
          <input type="text" [(ngModel)]="search" (ngModelChange)="onFilter()" placeholder="Search requests..."
            style="flex:1;min-width:200px;padding:0.5rem 0.75rem;font-size:0.8125rem;border:1px solid var(--rr-border);border-radius:0.375rem">
          <select [(ngModel)]="statusFilter" (ngModelChange)="onFilter()" style="padding:0.5rem 0.75rem;font-size:0.8125rem;border:1px solid var(--rr-border);border-radius:0.375rem">
            <option value="">All Statuses</option>
            <option *ngFor="let s of statusOptions" [value]="s.value">{{ s.label }}</option>
          </select>
          <select [(ngModel)]="priorityFilter" (ngModelChange)="onFilter()" style="padding:0.5rem 0.75rem;font-size:0.8125rem;border:1px solid var(--rr-border);border-radius:0.375rem">
            <option value="">All Priorities</option>
            <option value="Critical">Critical</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
          <select [(ngModel)]="engineFilter" (ngModelChange)="onFilter()" style="padding:0.5rem 0.75rem;font-size:0.8125rem;border:1px solid var(--rr-border);border-radius:0.375rem">
            <option value="">All Engines</option>
            <option *ngFor="let e of engineTypes" [value]="e">{{ e }}</option>
          </select>
        </div>
      </div>

      <div class="card" style="padding:0;overflow:hidden">
        <table style="width:100%;border-collapse:collapse">
          <thead>
            <tr style="background:var(--rr-platinum)">
              <th class="th">Reference</th>
              <th class="th">Title</th>
              <th class="th">Anomaly</th>
              <th class="th">Engine</th>
              <th class="th">MRO</th>
              <th class="th">Status</th>
              <th class="th">Priority</th>
              <th class="th">Date</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let r of requests"
                [routerLink]="['/dashboard/requests', r.id]"
                class="table-row">
              <td class="td" style="font-weight:500">{{ r.referenceNumber }}</td>
              <td class="td" style="max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ r.title }}</td>
              <td class="td muted">{{ r.anomalyType }}</td>
              <td class="td muted">{{ r.engineType }}</td>
              <td class="td muted" style="max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ r.mroOrganisation }}</td>
              <td class="td"><span class="badge" [ngClass]="getStatusCss(r.status)">{{ getStatusLabel(r.status) }}</span></td>
              <td class="td"><span class="badge" [ngClass]="r.priority.toLowerCase()">{{ r.priority }}</span></td>
              <td class="td muted">{{ formatDate(r.createdAt) }}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div *ngIf="totalCount > pageSize" style="display:flex;justify-content:center;gap:0.5rem;margin-top:1rem">
        <button class="btn-outline" (click)="changePage(page - 1)" [disabled]="page <= 1" style="padding:0.375rem 0.75rem;font-size:0.8125rem">Prev</button>
        <span style="padding:0.375rem 0.75rem;font-size:0.8125rem;color:var(--rr-muted)">{{ page }} / {{ totalPages }}</span>
        <button class="btn-outline" (click)="changePage(page + 1)" [disabled]="page >= totalPages" style="padding:0.375rem 0.75rem;font-size:0.8125rem">Next</button>
      </div>
    </div>
  `,
  styles: [`
    .th { text-align:left;padding:0.625rem 0.75rem;font-size:0.6875rem;font-weight:600;color:var(--rr-muted);text-transform:uppercase;letter-spacing:0.05em; }
    .td { padding:0.625rem 0.75rem;font-size:0.8125rem; }
    .muted { color: var(--rr-muted); }
    .table-row { border-top:1px solid var(--rr-border);cursor:pointer;transition:background 0.1s; }
    .table-row:hover { background: #F9FAFB; }
  `]
})
export class RequestsComponent implements OnInit {
  requests: VarianceRequestSummary[] = [];
  engineTypes: string[] = [];
  search = '';
  statusFilter = '';
  priorityFilter = '';
  engineFilter = '';
  page = 1;
  pageSize = 20;
  totalCount = 0;
  totalPages = 1;
  statusOptions = Object.entries(STATUS_LABELS).map(([value, label]) => ({ value, label }));

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.api.getEngineTypes().subscribe(d => this.engineTypes = d);
    this.loadRequests();
  }

  onFilter(): void { this.page = 1; this.loadRequests(); }
  changePage(p: number): void { this.page = p; this.loadRequests(); }

  loadRequests(): void {
    this.api.getRequests({
      page: this.page, pageSize: this.pageSize,
      status: this.statusFilter || undefined,
      priority: this.priorityFilter || undefined,
      engineType: this.engineFilter || undefined,
      search: this.search || undefined,
      sortBy: 'createdAt', sortDir: 'desc'
    }).subscribe(r => {
      this.requests = r.items;
      this.totalCount = r.totalCount;
      this.totalPages = Math.ceil(r.totalCount / this.pageSize);
    });
  }

  getStatusLabel(s: string): string { return STATUS_LABELS[s] || s; }
  getStatusCss(s: string): string { return STATUS_CSS[s] || ''; }
  formatDate(d: string): string { return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }); }
}
